### ISSUE TITLE
마스크 판매 현황 API가 종료되었습니다.

### ISSUE THREAD

**Issue by bxvcd-732** [jihyuk0252/discord-bot#1]
제작하신 봇에 마스크 판매 API를 사용하는 기능이 있습니다. 공적 마스크 판매가 종료됨에 따라, 해당 API도 종료되었습니다. 봇을 수정하셔야 할 것 같습니다.

**Comment by withJihyuk** [comment]
앗 이제서야 봤네요 삭제하였습니다! 감사합니다!
